import { useState, useRef } from 'react'
import { useNavigate } from 'react-router-dom'

// Domain-specific vocabulary lists for orange highlighting
const DOMAIN_VOCAB = {
  STEM: ['hypothesis','algorithm','derivative','integral','photosynthesis','mitosis','quantum','velocity','acceleration','entropy','molecule','chromosome','polynomial','theorem','circuit','electrode','catalyst','frequency','wavelength','amplitude'],
  Humanities: ['rhetoric','epistemology','hermeneutics','dialectic','phenomenology','ontology','metaphor','allegory','paradigm','discourse','narrative','ideology','sovereignty','hegemony','postmodernism'],
  'Social Sciences': ['sociology','anthropology','demographics','qualitative','quantitative','ethnography','correlation','regression','paradigm','hypothesis','variable','methodology','empirical','normative']
}

function App() {
  const navigate = useNavigate()
  const [text, setText] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [fileName, setFileName] = useState(null)
  const [progress, setProgress] = useState('')
  const [progressPct, setProgressPct] = useState(0)
  const [dragging, setDragging] = useState(false)
  const [showComplex, setShowComplex] = useState(true)
  const [showDomainVocab, setShowDomainVocab] = useState(true)
  const fileInputRef = useRef()

  const saveToHistory = (data, file) => {
    const history = JSON.parse(localStorage.getItem('educas_history') || '[]')
    history.unshift({ ...data, fileName: file || 'Manual Text Input', date: new Date().toLocaleDateString() })
    localStorage.setItem('educas_history', JSON.stringify(history.slice(0, 50)))
  }

  const processFile = async (file) => {
    if (!file) return
    if (file.size > 5 * 1024 * 1024) return alert('File exceeds 5MB limit!')
    setFileName(file.name)
    setLoading(true)
    setResult(null)
    setProgressPct(20)
    setProgress('📤 Uploading file...')
    try {
      const formData = new FormData()
      formData.append('file', file)
      setProgressPct(50)
      setProgress('📖 Extracting text...')
      const res = await fetch('http://localhost:8000/upload', { method: 'POST', body: formData })
      setProgressPct(80)
      setProgress('🤖 AI is analyzing...')
      const data = await res.json()
      setProgressPct(100)
      setProgress('📊 Preparing results...')
      setResult(data)
      saveToHistory(data, file.name)
    } catch (e) { alert('File upload failed!') }
    setLoading(false)
    setProgress('')
    setProgressPct(0)
  }

  const handleFile = (e) => processFile(e.target.files[0])
  const handleDrop = (e) => {
    e.preventDefault()
    setDragging(false)
    const file = e.dataTransfer.files[0]
    if (file) processFile(file)
  }

  const analyzeText = async () => {
    if (!text.trim()) return alert('Please enter some text!')
    setLoading(true)
    setResult(null)
    setProgressPct(20)
    setProgress('📤 Sending text...')
    try {
      setProgressPct(50)
      setProgress('🤖 AI is analyzing...')
      const res = await fetch('http://localhost:8000/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      })
      setProgressPct(85)
      setProgress('📊 Preparing results...')
      const data = await res.json()
      setProgressPct(100)
      setResult(data)
      saveToHistory(data, null)
    } catch (e) { alert('Server not running!') }
    setLoading(false)
    setProgress('')
    setProgressPct(0)
  }

  const downloadReport = () => {
    if (!result) return
    const content = `
EDUCAS - EDUCATIONAL CONTENT ANALYSIS REPORT
=============================================
File/Text Analyzed: ${fileName || 'Manual Text Input'}
Date: ${new Date().toLocaleDateString()}

ANALYSIS RESULTS
----------------
Subject Domain:    ${result.domain}
Specific Subject:  ${result.subject}
Difficulty Level:  ${result.difficulty}
Suitable For:      ${result.suitableFor}
Confidence Score:  ${result.confidence ? (result.confidence * 100).toFixed(1) + '%' : 'N/A'}

READABILITY METRICS
-------------------
Flesch Reading Ease:   ${result.readability?.fleschScore ?? 'N/A'}
SMOG Grade:            ${result.readability?.smogScore ?? 'N/A'}
Reading Level:         ${result.readability?.readingLevel ?? 'N/A'}
Avg Sentence Length:   ${result.readability?.avgSentenceLength ?? 'N/A'} words
Complex Sentences:     ${result.readability?.complexSentences ?? 'N/A'}

AI SUMMARY
----------
${result.summary}

RECOMMENDATIONS
---------------
${result.recommendations}

=============================================
Generated by EduCAS - Educational Content Analysis System
University of Hail - College of Computer Science and Engineering
    `.trim()
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'EduCAS_Report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  // Highlight complex (yellow) and domain vocab (orange)
  const highlightText = (inputText) => {
    if (!inputText) return null
    const domainWords = result?.domain ? (DOMAIN_VOCAB[result.domain] || []) : []
    const sentences = inputText.match(/[^.!?]+[.!?]+/g) || [inputText]

    return sentences.map((sentence, si) => {
      const wordCount = sentence.trim().split(/\s+/).length
      const isComplex = showComplex && wordCount > 25

      // Split sentence into words for orange highlighting
      const parts = sentence.split(/(\s+)/)
      const highlighted = parts.map((part, wi) => {
        const clean = part.toLowerCase().replace(/[^a-z]/g, '')
        const isDomainWord = showDomainVocab && domainWords.includes(clean)
        if (isDomainWord) {
          return <span key={wi} className="domain-word" title="Domain-specific vocabulary">{part}</span>
        }
        return part
      })

      return (
        <span key={si} className={isComplex ? 'complex-sentence' : ''} title={isComplex ? `Complex sentence (${wordCount} words)` : ''}>
          {highlighted}
        </span>
      )
    })
  }

  const getConfidenceColor = (conf) => {
    if (!conf) return '#90a4ae'
    if (conf >= 0.85) return '#2e7d32'
    if (conf >= 0.65) return '#f9a825'
    return '#c62828'
  }

  const getFleschLabel = (score) => {
    if (score == null) return 'N/A'
    if (score >= 90) return 'Very Easy'
    if (score >= 70) return 'Easy'
    if (score >= 60) return 'Standard'
    if (score >= 50) return 'Fairly Difficult'
    if (score >= 30) return 'Difficult'
    return 'Very Difficult'
  }

  return (
    <div className="app">
      <nav className="navbar">
        <div className="nav-logo">EduCAS</div>
        <div className="nav-links">
          <button onClick={() => navigate('/')} className="nav-btn">Home</button>
          <button onClick={() => navigate('/analyze')} className="nav-btn active">Analyze</button>
          <button onClick={() => navigate('/history')} className="nav-btn">History</button>
          <button onClick={() => navigate('/stats')} className="nav-btn">Statistics</button>
          <button onClick={() => navigate('/about')} className="nav-btn">About</button>
          <button onClick={() => navigate('/login')} className="nav-btn login-btn">Login</button>
        </div>
      </nav>

      <div className="app-inner">
        <header>
          <div className="header-logo">🎓</div>
          <h1>EduCAS</h1>
          <p>Educational Content Analysis System</p>
          <p className="header-sub">University of Hail · College of Computer Science</p>
        </header>

        <main>
          <div className="input-section">
            <h2>📄 Upload a File</h2>
            <div
              className={"upload-box" + (dragging ? " dragging" : "")}
              onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
              onDragLeave={() => setDragging(false)}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current.click()}
            >
              <input ref={fileInputRef} type="file" accept=".pdf,.docx,.txt" onChange={handleFile} style={{ display: 'none' }} />
              <div className="upload-content">
                <span className="upload-icon">{dragging ? '📂' : '📁'}</span>
                <p>{fileName ? ('✅ ' + fileName) : dragging ? 'Drop it here!' : 'Drag & Drop or Click to Upload'}</p>
                <small>PDF, DOCX, TXT · Max 5MB</small>
              </div>
            </div>

            <div className="divider">— OR —</div>
            <h2>✏️ Paste Text</h2>
            <textarea rows={8} placeholder="Paste a paragraph from a textbook, article, or document..." value={text} onChange={e => setText(e.target.value)} />
            <button onClick={analyzeText} disabled={loading}>
              {loading ? '⏳ Analyzing...' : '🔍 Analyze Content'}
            </button>
          </div>

          {loading && (
            <div className="progress-box">
              <div className="spinner"></div>
              <p>{progress}</p>
              <div className="progress-bar">
                <div className="progress-fill" style={{ width: progressPct + '%', transition: 'width 0.5s ease', animation: 'none', background: 'linear-gradient(90deg, #1a73e8, #00897b)' }}></div>
              </div>
              <small className="progress-pct">{progressPct}%</small>
            </div>
          )}

          {result && !loading && (
            <div className="results">
              <div className="results-header">
                <h2>📊 Analysis Results</h2>
                <button className="download-btn" onClick={downloadReport}>⬇️ Download Report</button>
              </div>

              <div className="cards">
                <div className="card"><h3>📚 Subject Domain</h3><p className="big">{result.domain}</p></div>
                <div className="card"><h3>🎯 Specific Subject</h3><p className="big">{result.subject}</p></div>
                <div className="card"><h3>📖 Difficulty Level</h3><p className="big">{result.difficulty}</p></div>
                <div className="card"><h3>✅ Suitable For</h3><p className="big">{result.suitableFor}</p></div>
              </div>

              {result.confidence !== undefined && (
                <div className="confidence-box">
                  <h3>🎯 AI Confidence Score</h3>
                  <div className="confidence-bar-wrap">
                    <div className="confidence-bar-track">
                      <div className="confidence-bar-fill" style={{ width: (result.confidence * 100).toFixed(1) + '%', background: getConfidenceColor(result.confidence) }}></div>
                    </div>
                    <span className="confidence-pct" style={{ color: getConfidenceColor(result.confidence) }}>
                      {(result.confidence * 100).toFixed(1)}%
                    </span>
                  </div>
                  <small>{result.confidence >= 0.85 ? '✅ High Confidence' : result.confidence >= 0.65 ? '⚠️ Medium Confidence' : '❌ Low Confidence'}</small>
                </div>
              )}

              {result.readability && (
                <div className="readability-box">
                  <h3>📏 Readability Metrics</h3>
                  <div className="readability-grid">
                    <div className="read-card">
                      <span className="read-value">{result.readability.fleschScore ?? 'N/A'}</span>
                      <span className="read-label">Flesch Score</span>
                      <span className="read-sub">{getFleschLabel(result.readability.fleschScore)}</span>
                    </div>
                    <div className="read-card">
                      <span className="read-value">{result.readability.smogScore ?? 'N/A'}</span>
                      <span className="read-label">SMOG Grade</span>
                      <span className="read-sub">grade level</span>
                    </div>
                    <div className="read-card">
                      <span className="read-value">{result.readability.avgSentenceLength ?? 'N/A'}</span>
                      <span className="read-label">Avg Sentence Length</span>
                      <span className="read-sub">words per sentence</span>
                    </div>
                    <div className="read-card">
                      <span className="read-value">{result.readability.complexSentences ?? 'N/A'}</span>
                      <span className="read-label">Complex Sentences</span>
                      <span className="read-sub">over 25 words</span>
                    </div>
                    <div className="read-card">
                      <span className="read-value">{result.readability.readingLevel ?? 'N/A'}</span>
                      <span className="read-label">Reading Level</span>
                      <span className="read-sub">grade level</span>
                    </div>
                  </div>
                </div>
              )}

              {/* TOGGLE CONTROLS */}
              <div className="toggle-controls">
                <h3>🎨 Highlight Controls</h3>
                <div className="toggles">
                  <label className="toggle-label">
                    <input type="checkbox" checked={showComplex} onChange={e => setShowComplex(e.target.checked)} />
                    <span className="toggle-dot yellow-dot"></span>
                    Complex Sentences (over 25 words)
                  </label>
                  <label className="toggle-label">
                    <input type="checkbox" checked={showDomainVocab} onChange={e => setShowDomainVocab(e.target.checked)} />
                    <span className="toggle-dot orange-dot"></span>
                    Domain-Specific Vocabulary
                  </label>
                </div>
              </div>

              <div className="summary-box">
                <h3>💡 AI Summary</h3>
                <div className="highlight-legend">
                  <span className="legend-dot yellow-bg"></span><small>Complex sentence</small>
                  <span className="legend-dot orange-bg" style={{marginLeft:'12px'}}></span><small>Domain vocabulary</small>
                </div>
                <p className="highlighted-text">{highlightText(result.summary)}</p>
              </div>

              <div className="summary-box">
                <h3>📝 Recommendations</h3>
                <p>{result.recommendations}</p>
              </div>
            </div>
          )}
        </main>

        <footer>
          <p>EduCAS · University of Hail · Department of Software Engineering</p>
        </footer>
      </div>
    </div>
  )
}

export default App